apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: monitoring.gitops-with-tanzu.github.com
spec:
  displayName: GitOps with Tanzu - Monitoring
  longDescription: Monitoring packages for Tanzu clusters
  shortDescription: Monitoring packages for Tanzu clusters
  providerName: GitOps with Tanzu
  maintainers:
  - name: Mohamed Hadrouj
  supportDescription: Go to github.com/hadrouj/gitops-with-tanzu for documentation
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: monitoring.gitops-with-tanzu.github.com.1.0.0
spec:
  refName: monitoring.gitops-with-tanzu.github.com
  version: 1.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/hadrouj/gitops-with-tanzu-monitoring:stable
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
