apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
spec:
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.0.0"
  serviceAccountName: core-default-sa
  values:
  - secretRef:
      name: contour-pkg-values
