apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metallb
spec:
  packageRef:
    refName: metallb.extra.tanzu.vmware.com
    versionSelection:
      constraints: 0.10.3
  serviceAccountName: core-default-sa
  values:
  - secretRef:
      name: metallb-pkg-values
